studybud/base/urls.py
from django.urls import path

from . import views

app_name = 'base'

urlpatterns = [
    path('', views.index, name='home'),
    path('room/<int:id>/', views.room, name='room')
]

studybud/studybud/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('base.urls'))
]

studybud/base/models.py
from django.db import models
from django.contrib.auth.models import User


class Topic(models.Model):
    name = models.CharField(max_length=256)

    def __str__(self):
        return self.name


class Category(models.Model):
    pass


class Room(models.Model):
    host = models.ForeignKey(User, null=True, on_delete=models.SET_NULL)
    topic = models.ForeignKey(Topic, null=True, on_delete=models.SET_NULL)
    name = models.CharField(max_length=256)
    description = models.TextField(null=True, blank=True)
    # participants =
    updated = models.DateTimeField(auto_now=True)
    created = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.name


class Message(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    room = models.ForeignKey(Room, on_delete=models.CASCADE)
    body = models.TextField()
    updated = models.DateTimeField(auto_now=True)
    created = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.body[:50]

studybud/base/views.py
from django.shortcuts import render

from .models import Room


def index(request):
    template = 'index.html'
    rooms = Room.objects.all()
    context = {'rooms': rooms}
    return render(request, template, context)


def room(request, id):
    template = 'room.html'
    room = Room.objects.get(id=id)
    context = {'room': room}
    return render(request, template, context)

studybud/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <title>{% block title %}APP NAME{% endblock %}</title>
</head>
<body>
{% include "includes/header.html" %}
{% block content %}{% endblock %}
</body>
</html>

studybud/templates/includes/header.html
<header>
  <a href="{% url 'base:home' %}">homepage</a>
  <hr>
</header>

studybud/templates/index.html
{% extends 'base.html' %}

{% block content %}
  <h1>Homepage</h1>
  {% for room in rooms %}
    <div>
      <h5>
        <p>{{ room.topic.name }}</p>
        <p>{{ room.id }} -- <a href="{% url 'base:room' room.id %}">{{ room.name }}</a></p>
        {{ room.host.username }}
      </h5>
      <hr>
    </div>
  {% endfor %}
{% endblock %}

studybud/templates/room.html
{% extends 'base.html' %}

{% block content %}
  <h1>{{ room.name }}</h1>
  <h3>{{ room.description }}</h3>
{% endblock %}